# version: "3.9"
services:
  budget-web-app:
    build: .
    container_name: memoit
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate && rails server -b 0.0.0.0"

    ## Ports will be handled via nginx . Uncomment this when running locally
    
    # ports:
    #   - 80:3000

    depends_on:
      - memoit-app-db

  memoit-app-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
