route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - to: your-email@gmail.com
      from: your-email@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: your-email@gmail.com
      auth_password: your password
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
